---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "dataplane.strimzi.broker.fullname" . }}
  labels:
    {{- include "dataplane.labels" . | nindent 4 }}
  {{- with .Values.strimzi.broker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  kafka:
    version: {{ .Values.strimzi.broker.version }}
    replicas: {{ .Values.strimzi.broker.replicas }}
    listeners:
      - name: plain
        port: {{ .Values.strimzi.broker.listener.plain }}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.strimzi.broker.listener.tls }}
        type: internal
        tls: true
      - name: external
        port: {{ .Values.strimzi.broker.listener.external }}
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            {{- with .Values.strimzi.brokerlisterner.annotations }}
            annotations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          brokers:
            - broker: 0
              {{- with .Values.strimzi.brokerlisterner.annotations }}
              annotations:
                {{- toYaml . | nindent 16 }}
              {{- end }}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.dataplane.protocol.version: "2.7"
    storage:
      type: persistent-claim
      size: 200Gi
      class: px-replicated
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: px-replicated
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  cruiseControl: {}
