{{- $fullName := include "dataplane.strimzi.connect.fullname" . -}}

{{- range $db := .Values.cdc.postgres }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ $fullName }}-{{ $db.servername }}-{{ $db.dbname }}
  labels:
    strimzi.io/cluster: {{ $fullName }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: {{ $db.hostname }}
    database.port: "{{ $db.port | default 5432 }}"
    database.user: "${env:POSTGRES_USER}"
    database.password: "${env:POSTGRES_PASS}"
    database.server.name: "{{ $db.servername }}"
    database.dbname: "{{ $db.dbname }}"
    tasks.max: "1"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.schemas.enable: "false"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
{{- end }}
