---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ include "dataplane.strimzi.connect.fullname" . }}
  {{- with .Values.strimzi.connect.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.strimzi.connect.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  build:
    output:
      type: docker
      image: {{ .Values.strimzi.connect.image }}
    plugins:
      - name: debezium-connector-postgres
        artifacts:
          - type: maven
            group: io.debezium
            artifact: debezium-connector-postgres
            version: {{ .Values.strimzi.debezium.version }}
      - name: debezium-connector-mysql
        artifacts:
          - type: maven
            group: io.debezium
            artifact: debezium-connector-mysql
            version: {{ .Values.strimzi.debezium.version }}
  replicas: {{ .Values.strimzi.connect.replicas }}
  bootstrapServers: {{ include "dataplane.strimzi.kafka.bootstrap" . }}:{{ .Values.strimzi.kafka.listener.plain.port }}
  {{- with .Values.strimzi.connect.config }}
  config:
    {{- toYaml . | nindent 4 }}
  {{- end }}
