{{- $fullName := include "dataplane.strimzi.connect.fullname" . -}}
{{- $registryName := include "dataplane.registry.fullname" . -}}
{{- $registryPort := .Values.registry.service.port -}}

{{- range $db := .Values.cdc.postgres }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ $fullName }}-{{ $db.servername }}-{{ $db.dbname }}
  labels:
    strimzi.io/cluster: {{ $fullName }}
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: {{ $db.hostname }}
    database.port: "{{ $db.port | default 5432 }}"
    database.user: "${env:POSTGRES_USER}"
    database.password: "${env:POSTGRES_PASS}"
    database.server.name: "{{ $db.servername }}"
    database.dbname: "{{ $db.dbname }}"
    tasks.max: "1"
    key.converter: io.confluent.connect.avro.AvroConverter
    key.converter.schema.registry.url: http://{{ $registryName }}:{{ $registryPort }}
    value.converter: io.confluent.connect.avro.AvroConverter
    value.converter.schema.registry.url: http://{{ $registryName }}:{{ $registryPort }}
    transforms: Reroute
    transforms.Reroute.type: io.debezium.transforms.ByLogicalTableRouter
    transforms.Reroute.topic.regex: (.*)
    transforms.Reroute.topic.replacement: cdc.$1
{{- end }}
