{{- $replicas := (int .Values.strimzi.kafka.replicas) }}
{{- $brokerCount := (int .Values.strimzi.kafka.brokers) }}
{{- $kafkaAnnotations := .Values.strimzi.kafka.annotations }}
{{- $externalAnnotations := .Values.strimzi.kafka.listener.external.annotations }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ include "dataplane.strimzi.kafka.fullname" . }}
  labels:
    {{- include "dataplane.strimzi.labels" . | nindent 4 }}
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  {{- with $kafkaAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  kafka:
    version: {{ .Values.strimzi.kafka.version }}
    listeners:
      - name: plain
        port: {{ .Values.strimzi.kafka.listener.plain.port }}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.strimzi.kafka.listener.tls.port }}
        type: internal
        tls: true
      - name: external
        port: {{ .Values.strimzi.kafka.listener.external.port }}
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            {{- with $externalAnnotations }}
            annotations:
              {{- toYaml . | nindent 14 }}
            {{- end }}
    {{- with .Values.strimzi.kafka.config }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
  {{- if (gt $replicas 1) }}
  cruiseControl: {}
  {{- end }}
