---
metabase:
  admin:
    email: metabase@nephelai.io
  ingress:
    enabled: true
    className: nginx-private
    hostName: metabase.nephelai.io
cdc:
  postgres:
    - hostname: pagilahost
      connector: pagila-connector
      id: pagila
      dbname: pagila
      exclude:
        - "public.staff"
      partitions:
        - source: "public.payment.*"
          sink: "payment"
strimzi:
  connect:
    secret: "metabase-pagila-db"
  kafka:
    storage:
      class: standard
  zookeeper:
    storage:
      class: standard
zalando:
  metabase:
    class: standard
