{{- $connectSvc := printf "%s-%s" (include "dataplane.strimzi.connect.fullname" .) "connect-api" }}
{{- $connectPort := 8083 }}
{{- $svcName :=  include "dataplane.registry.fullname" . }}
{{- $svcPort := .Values.registry.service.port -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $svcName }}-connector-restart
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: connector-restart
          securityContext:
            {{- toYaml .Values.registry.securityContext | nindent 12 }}
          image: {{ .Values.util.image.repository }}:{{ .Values.util.image.tag }}
          imagePullPolicy: {{ .Values.registry.hook.pullPolicy }}
          resources:
            {{- toYaml .Values.util.resources | nindent 12 }}
          command:
            - "sh"
            - "-c"
            - >-
              until curl -s http://{{ $svcName }}:{{ $svcPort }}/ -o /dev/null; do
                echo "[$(date -Iseconds)] [INFO] [connector-restart] waiting for registry service";
                sleep 10;
              done;
              echo registry service up;
              until curl -s http://{{ $connectSvc }}:{{ $connectPort }}/ -o /dev/null; do
                echo "[$(date -Iseconds)] [INFO] [connector-restart] waiting for connect api service";
                sleep 10;
              done;
              echo "[$(date -Iseconds)] [INFO] [connector-restart] connect api service up";
              sleep 10;
              echo "[$(date -Iseconds)] [INFO] [connector-restart] restarting connectors";
              curl -s http://{{ $connectSvc }}:{{ $connectPort }}/connectors | jq '.[]' -r |
                xargs -I{} curl -s -XPOST http://{{ $connectSvc }}:{{ $connectPort }}/connectors/{}/restart;
              echo "[$(date -Iseconds)] [INFO] [connector-restart] connectors restarted";
              echo "[$(date -Iseconds)] [INFO] [connector-restart] restarting tasks";
              curl -s http://{{ $connectSvc }}:{{ $connectPort }}/connectors | jq '.[]' -r |
                xargs -I{} bash -c "curl -s http://{{ $connectSvc }}:{{ $connectPort }}/connectors/{}/tasks |
                   jq 'map(.id.task) | .[]' -r |
                   xargs -I[] curl -s -XPOST http://{{ $connectSvc }}:{{ $connectPort }}/connectors/{}/tasks/[]/restart"
              echo "[$(date -Iseconds)] [INFO] [connector-restart] tasks restarted";
