---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dataplane.registry.fullname" . }}
  labels:
    {{- include "dataplane.registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - port: {{ .Values.registry.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dataplane.registry.selectorLabels" . | nindent 4 }}
