---
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cdc:

    postgres: []
    mysql: []

strimzi:

  kafka:
    version: "3.2.3"
    replicas: 3
    brokers: 4
    annotations: {}
    config: {}
    listener:
      plain:
        port: 9092
      tls:
        port: 9093
      external:
        port: 9094
        annotations: {}
    storage:
      size: 10Gi
      class: ""

  connect:
    image: nephelaiio/dataplane-connect:latest
    replicas: 3
    config:
      group.id: connect-cluster
      offset.storage.topic: connect.cluster.offsets
      config.storage.topic: connect.cluster.configs
      status.storage.topic: connect.cluster.status
      config.storage.replication.factor: 2
      offset.storage.replication.factor: 2
      status.storage.replication.factor: 2
    annotations:
      strimzi.io/use-connector-resources: "true"

  zookeeper:
    replicas: 3
    storage:
      size: 10Gi
      class: ""

zalando:

  metabase:
    name: metabase
    version: 14
    loadBalancer: false
    instances: 2
    volume: 10Gi
    serviceAnnotations: {}
    allowedSourceRanges:
      - 127.0.0.1
    user: metabase

  warehouse:
    name: warehouse
    version: 14
    loadBalancer: false
    instances: 2
    volume: 10Gi
    serviceAnnotations: {}
    allowedSourceRanges:
      - 127.0.0.1
    user: strimzi

metabase:

  replicaCount: 2

  image:
    repository: metabase/metabase
    pullPolicy: IfNotPresent
    tag: ""

  ingress:
    enabled: false
    annotations: {}
    hostName: ""
    className: ""
    secretName: ""

  service:
    type: ClusterIP
    port: 3000

  podEnvironmentVars:
    - name: "MB_REDIRECT_ALL_REQUESTS_TO_HTTPS"
      value: "true"

  securityContext: {}
  podSecurityContext: {}
  podAnnotations: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

registry:

  image:
    repository: confluentinc/cp-schema-registry
    pullPolicy: IfNotPresent
    tag: "5.4.10"

  service:
    type: ClusterIP
    port: 8081

  podEnvironmentVars:
    - name: "MB_REDIRECT_ALL_REQUESTS_TO_HTTPS"
      value: "true"

  securityContext: {}

  podSecurityContext: {}

  podAnnotations: {}

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}
