---
replicaCount: 2

image:
  repository: metabase/metabase
  pullPolicy: IfNotPresent
  tag: "v0.44.2"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: []
  hostName: ""
  className: ""
  secretName: ""

zalando:
  db:
    name: db
    version: 14
    loadBalancer: false
    instances: 2
    volume: 10Gi
    serviceAnnotations: []

config:
  adminEmail: info@example.org

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
