---
- name: converge

  hosts: localhost

  gather_facts: false

  roles:

    - nephelaiio.plugins

  tasks:

    - name: wait for strimzi crd deployment
      kubernetes.core.k8s_info:
        api_version: v1
        kind: CustomResourceDefinition
        name: kafkas.kafka.strimzi.io
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        wait: true
        wait_condition:
          status: True
          type: NamesAccepted
        wait_sleep: 10
        wait_timeout: 300

    - name: wait for zalando crd deployment
      kubernetes.core.k8s_info:
        api_version: v1
        kind: CustomResourceDefinition
        name: postgresqls.acid.zalan.do
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        wait: true
        wait_condition:
          status: True
          type: NamesAccepted
        wait_sleep: 10
        wait_timeout: 300

    - name: create metabase namespace
      kubernetes.core.k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: "{{ dataplane_namespace }}"
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"

    - name: deploy source pagila db
      kubernetes.core.k8s:
        state: present
        kubeconfig: "{{ k8s_kubeconfig | default(omit) }}"
        resource_definition: "{{ _definition }}"
      vars:
        _definition: |
          apiVersion: acid.zalan.do/v1
          kind: postgresql
          metadata:
            name: {{ dataplane_pagila_team }}-{{ dataplane_pagila_db }}
            namespace: {{ dataplane_pagila_namespace }}
          spec:
            teamId: {{ dataplane_pagila_team }}
            volume:
              size: 1Gi
            numberOfInstances: 1
            allowedSourceRanges:
              - 0.0.0.0/0
            enableMasterLoadBalancer: true
            serviceAnnotations:
              metallb.universe.tf/address-pool: private
            users:
              zalando:
                - superuser
                - createdb
              {{ dataplane_pagila_user }}:
                - login
                - replication
                - createdb
            databases:
              {{ dataplane_pagila_db }}: {{ dataplane_pagila_user }}
            postgresql:
              version: "14"
              parameters:
                wal_level: logical

    - name: wait for database cluster startup
      ansible.builtin.fail:
        msg: "zalando clusters failed to come up on time"
      vars:
        cluster_failed: "{{ cluster_status | rejectattr('status.PostgresClusterStatus', 'equalto', 'Running') | map(attribute='metadata.name') }}"
        cluster_status: "{{ cluster_query | selectattr('status', 'defined') }}"
        cluster_query: "{{
          query(
            'kubernetes.core.k8s',
            api_version='acid.zalan.do/v1',
            kind='postgresql',
            kubeconfig=k8s_kubeconfig
          )}}"
      retries: 15
      delay: 30
      until: cluster_failed | length == 0
      failed_when:
        - (cluster_status | length) != (cluster_query | length)
        - cluster_failed | length > 0

    - name: deploy dataplane helm chart
      kubernetes.core.helm:
        state: present
        name: "{{ dataplane_chart }}"
        chart_ref: "{{ dataplane_path }}/charts/dataplane"
        release_namespace: "{{ dataplane_namespace }}"
        create_namespace: true
        force: true
        wait: false
        timeout: 30m
        kubeconfig: "{{ k8s_kubeconfig }}"
        binary_path: "{{ k8s_helm_bin }}"
        values: "{{ dataplane_chart_values }}"

    - name: wait for database cluster startup
      ansible.builtin.fail:
        msg: "zalando clusters failed to come up on time"
      vars:
        cluster_failed: "{{ cluster_status | rejectattr('status.PostgresClusterStatus', 'equalto', 'Running') | map(attribute='metadata.name') }}"
        cluster_status: "{{ cluster_query | selectattr('status', 'defined') }}"
        cluster_query: "{{
          query(
            'kubernetes.core.k8s',
            api_version='acid.zalan.do/v1',
            kind='postgresql',
            kubeconfig=k8s_kubeconfig
          )}}"
      retries: 15
      delay: 30
      until: cluster_failed | length == 0
      failed_when:
        - (cluster_status | length) != (cluster_query | length)
        - cluster_failed | length > 0

    - name: query pagila connection data
      ansible.builtin.set_fact:
        pagila_user: "{{ pagila_db_secret_data.data.username | b64decode }}"
        pagila_pass: "{{ pagila_db_secret_data.data.password | b64decode }}"
      vars:
        pagila_db_secret_name: "{{ dataplane_pagila_user }}-{{ dataplane_pagila_team }}-{{ dataplane_pagila_db }}"
        pagila_db_secret_data: "{{ secret_query | selectattr('metadata.name', 'equalto', pagila_db_secret_name) | first }}"
        secret_query: "{{
          query(
            'kubernetes.core.k8s',
            namespace=dataplane_pagila_namespace,
            kind='Secret',
            kubeconfig=k8s_kubeconfig
          )}}"

    - name: query pagila service data
      ansible.builtin.set_fact:
        pagila_host: "{{ pagila_db_svc_data.status.loadBalancer.ingress[0].ip }}"
      vars:
        pagila_db_svc_name: "{{ dataplane_pagila_team }}-{{ dataplane_pagila_db }}"
        pagila_db_svc_data: "{{ service_query | selectattr('metadata.name', 'equalto', pagila_db_svc_name) | first }}"
        service_query: "{{
          query(
            'kubernetes.core.k8s',
            namespace=dataplane_pagila_namespace,
            kind='Service',
            kubeconfig=k8s_kubeconfig
          )}}"

    - name: wait for database port open
      ansible.builtin.wait_for:
        host: "{{ pagila_host }}"
        port: 5432

    - name: create database
      community.postgresql.postgresql_db:
        name: "{{ dataplane_pagila_db }}"
        state: present
        login_user: "{{ pagila_user }}"
        login_password: "{{ pagila_pass }}"
        login_host: "{{ pagila_host }}"

    - name: create data tempdir
      ansible.builtin.tempfile:
        state: directory
        prefix: data
      register: datadir
      changed_when: false

    - block:

        - name: fetch pagila schema file
          ansible.builtin.get_url:
            url: https://github.com/devrimgunduz/pagila/raw/master/pagila-schema.sql
            dest: "{{ datadir.path }}/schema.sql"
          changed_when: false

        - name: fetch pagila data file
          ansible.builtin.get_url:
            url: https://github.com/devrimgunduz/pagila/raw/master/pagila-data.sql
            dest: "{{ datadir.path }}/data.sql"
          changed_when: false

        - name: concatenate pagila sql files
          ansible.builtin.shell: "cat {{ datadir.path }}/schema.sql {{ datadir.path }}/data.sql > {{ datadir.path }}/pagila.sql"

        - name: load pagila db data
          community.postgresql.postgresql_db:
            name: "{{ dataplane_pagila_db }}"
            state: restore
            login_user: "{{ pagila_user }}"
            login_password: "{{ pagila_pass }}"
            login_host: "{{ pagila_host }}"
            target: "{{ datadir.path }}/pagila.sql"
          changed_when: false

      always:

        - name: destroy data tempdir
          ansible.builtin.file:
            state: absent
            path: "{{ datadir.path }}"
          changed_when: false
