---
- name: destroy

  hosts: localhost

  gather_facts: true

  vars:

    kind_cluster_state: absent

  roles:

    - nephelaiio.plugins
    - nephelaiio.kind

  tasks:

    - name: delete certificate from edge truststore
      ansible.builtin.command: "certutil -d sql:$HOME/.pki/nssdb -D -n {{ k8s_cluster_name }}"
      changed_when: false
      ignore_errors: true
