---
- name: verify

  hosts: localhost

  gather_facts: false

  vars:

    k8s_deploy: false
    k8s_verify: true
    k8s_strimzi_verify: false
    k8s_ingress_verify: false
    k8s_volume_verify: false

  roles:

    - nephelaiio.plugins
    - nephelaiio.k8s
