---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ include "metabase.db.cluster" . }}
spec:
  teamId: {{ include "metabase.db.team" . }}
  volume:
    size: {{ .Values.zalando.db.volume }}
  numberOfInstances: {{ .Values.zalando.db.instances }}
  allowedSourceRanges:
    - 0.0.0.0/0
  enableMasterLoadBalancer: {{ .Values.zalando.db.loadBalancer }}
  {{- with .Values.zalando.serviceAnnotations }}
  serviceAnnotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  users:
    admin:
      - superuser
      - createdb
    {{ .Values.zalando.db.user }}: []
  databases:
    metabase: {{ .Values.zalando.db.user }}
  postgresql:
    version: "{{ .Values.zalando.db.version }}"
