---
{{- if .Values.metabase.ingress.enabled -}}
{{- $fullName := include "dataplane.metabase.fullname" . -}}
{{- $secretName := include "dataplane.metabase.ingress.secretName" . -}}
{{- $svcPort := .Values.metabase.service.port -}}
{{- if and .Values.metabase.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.metabase.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.metabase.ingress.annotations "kubernetes.io/ingress.class" .Values.metabase.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dataplane.labels" . | nindent 4 }}
  {{- with .Values.metabase.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.metabase.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.metabase.ingress.className }}
  {{- end }}
  tls:
    - hosts:
        - "{{ .Values.metabase.ingress.hostName }}"
      secretName: {{ $secretName }}
  rules:
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
{{- end }}
