---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: docker
on:

  push:
    tags:
      - "*"

jobs:

  docker:

    name: publish docker images
    runs-on: ubuntu-latest

    steps:

      - name: set up quemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: build and push connect image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:connect"
          push: true
          tags: nephelaiio/dataplane-connect:${{  github.ref_name }}

      - name: build and push util image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:util"
          push: true
          tags: nephelaiio/dataplane-util:${{ github.ref_name }}
