---
name: docker

on:
  push:
    tags:
      - "*"

jobs:
  docker:
    name: publish docker images
    runs-on: ubuntu-latest
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Set up quemu
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push connect image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:connect"
          push: true
          tags: nephelaiio/dataplane-connect:latest,nephelaiio/dataplane-connect:${{  github.ref_name }}

      - name: Build and push util image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:util"
          push: true
          tags: nephelaiio/dataplane-util:latest,nephelaiio/dataplane-util:${{ github.ref_name }}
