---
name: keepalive

on:
  schedule:
    - cron: "55 23 * * 4"

jobs:

  keepalive:

    name: Github Actions keepalive
    runs-on: ubuntu-latest

    steps:

      - name: check out the codebase
        uses: actions/checkout@v2

      - name: add keepalive commit
        uses: gautamkrishnar/keepalive-workflow@master
        with:
          commit_message: "Add CI Keepalive Commit"
          committer_username: "Ted Cook"
          committer_email: "Ted Cook@example.com"
          auto_push: true
