---
name: Molecule

on:

  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:

  run:
    working-directory: 'nephelaiio.k8s-cdc'

jobs:

  lint:

    name: lint
    runs-on: ubuntu-latest
    steps:

      - name: check out the codebase
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.k8s-cdc'

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install package requirements
        run: apt-get install -y python3-dev libpq-dev

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: lint code
        run: |
          set -e
          poetry run yamllint .
          poetry run ansible-lint .

  molecule:

    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - release: v0.16.0
            image: v1.24.6
          - release: v0.15.0
            image: v1.24.4
          - release: v0.15.0
            image: v1.23.10
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.k8s-cdc'

      - name: set up python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: run molecule tests.
        run: poetry run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          KIND_IMAGE: ${{ matrix.image }}
