---
name: molecule

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "55 23 * * 4"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - default
        include:
          - release: v0.18.0
            image: v1.25.8
          - release: v0.18.0
            image: v1.24.12
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Check out the codebase.
        uses: actions/checkout@v4

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install helm
        uses: azure/setup-helm@v4

      - name: Install helm diff plugin
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install package prerequisites
        run: sudo apt-get install -y postgresql-common libpq-dev

      - name: Install poetry
        run: pip3 install poetry

      - name: Install dependencies
        run: poetry install

      - name: Install make
        run: sudo apt-get install -y make

      - name: Run molecule tests
        run: ./bin/test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          KIND_RELEASE: ${{ matrix.release }}
          KIND_IMAGE: ${{ matrix.image }}
