---
name: release chart

on:

  pull_request:
    branches:
      - master
    paths:
      - 'charts/**'
  push:
    branches:
      - master
    paths:
      - 'charts/**'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1

      - name: configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: release chart
        uses: helm/chart-releaser-action@1.5.0
        env:
          CR_TOKEN: '${{ secrets.GH_TOKEN }}'
