---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
on:
  push:
    tags:
      - "*"

defaults:

  run:
    working-directory: 'nephelaiio.k8s-cdc'

jobs:

  release:

    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.k8s-cdc'

      - name: set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install poetry
        run: pip3 install poetry

      - name: install pips
        run: poetry install

      - name: trigger a new import on galaxy
        run: >-
          poetry run ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
