---
name: release chart

on:
  pull_request:
    branches:
      - master
    types:
      - closed
    paths:
      - 'charts/**/Chart.yaml'

jobs:
  release:
    if: github.event.pull_request.merged == true
    name: publish helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Update package cache
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Release chart
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: '${{ secrets.GH_TOKEN }}'
